name = "tauri"
version = "0.0.1"
target = "javascript"

description = "Gleam wrapper for the Tauri JavaScript API"
licences = ["MPL-2.0"]
repository = { type = "github", user = "beeauvin", repo = "tauri" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
